<?php

namespace App\Enums;

/**
 * Status of a single itinerary option under a trip (App\Models\Itinerary).
 * A trip can have several itineraries (e.g. "Option A/B/C") generated by
 * TripController::generateItinerary; DRAFT is the default for a freshly generated one.
 */
enum ItineraryStatus: string
{
    case DRAFT = 'draft';
    case PLANNING = 'planning';
    case CONFIRMED = 'confirmed';
    case IN_PROGRESS = 'in_progress';
    case COMPLETED = 'completed';
    case CANCELLED = 'cancelled';
}
